// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCFz2Hk6MWTrB3qHUnwb9wc6awWSoH58A',
    appId: '1:1046854793288:web:4e1d163ad9187329ff007d',
    messagingSenderId: '1046854793288',
    projectId: 'oracletz',
    authDomain: 'oracletz.firebaseapp.com',
    storageBucket: 'oracletz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlM6mqvaaO8CctlWG4GMgS3d6_NQAlDsY',
    appId: '1:1046854793288:android:e20a3234ab45c652ff007d',
    messagingSenderId: '1046854793288',
    projectId: 'oracletz',
    storageBucket: 'oracletz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqzE3MneuQZ4_vf5f1h6bcZ08ApBSqE3E',
    appId: '1:1046854793288:ios:9099decbab850520ff007d',
    messagingSenderId: '1046854793288',
    projectId: 'oracletz',
    storageBucket: 'oracletz.appspot.com',
    iosBundleId: 'com.example.oracleTz',
  );
}
